name: PullRequest and Push Regular Test
on: 
  pull_request:
  push:
    branches: 
      - master

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message, 'chore(ci)') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          yarn install --frozen-lockfile
          # yarn test

      - name: Build demo page test
        run: |
          cd example
          yarn install --frozen-lockfile
          yarn build

  pass-ci-chore-commits:
    if: ${{ contains(github.event.head_commit.message, 'chore(ci)') }}
    runs-on: ubuntu-latest
    steps:
      - run: 'echo pass'
          